import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft, Check, Mail, Phone, Sparkles, UserRound, X } from "lucide-react";
import HRLayout from "./HRLayout";
import { getCandidates, saveCandidates } from "./HRData";

export default function CandidateDetails(){const {id}=useParams();const candidates=getCandidates();const candidate=candidates.find(c=>String(c.id)===id)||candidates[0];const [status,setStatus]=useState(candidate.status);const changeStatus=(next)=>{setStatus(next);saveCandidates(candidates.map(c=>c.id===candidate.id?{...c,status:next,updated:"just now"}:c));};return <HRLayout title={candidate.name} subtitle={`${candidate.job} · Candidate #${candidate.id}`}>
 <Link className="hr-back-link" to="/hr/candidates"><ArrowLeft size={15}/> Back to candidates</Link>
 <div className="hr-detail-grid"><section className="hr-panel"><div className="hr-profile-head"><div className="hr-profile-avatar">{candidate.name.split(" ").map(x=>x[0]).join("")}</div><div><span className="hr-eyebrow">CANDIDATE PROFILE</span><h2>{candidate.name}</h2><p>{candidate.job} · {candidate.experience} experience</p></div><span className={`hr-status ${status.toLowerCase()}`}>{status.replace("_"," ")}</span></div><div className="hr-contact-grid"><div><Mail size={15}/><span>{candidate.email}</span></div><div><Phone size={15}/><span>{candidate.phone}</span></div><div><UserRound size={15}/><span>Referred by {candidate.referrer}</span></div></div><div className="hr-section"><h3>Skills</h3><div className="hr-chip-row">{candidate.skills.map(s=><span key={s}>{s}</span>)}</div></div><div className="hr-section"><h3>Referral context</h3><p className="hr-copy">This candidate was submitted through the employee referral programme. HR can review the profile, AI score and progress the candidate through the hiring pipeline.</p></div></section>
 <aside className="hr-panel"><h3>AI screening</h3><div className="hr-score-large"><Sparkles size={18}/><strong>{candidate.score}%</strong><span>match score</span></div><div className="hr-ai-bars"><div><span>Technical skills</span><b style={{width:`${Math.min(100,candidate.score+2)}%`}}/></div><div><span>Experience</span><b style={{width:`${Math.max(60,candidate.score-5)}%`}}/></div><div><span>Role relevance</span><b style={{width:`${Math.min(100,candidate.score+5)}%`}}/></div></div><div className="hr-action-stack"><button onClick={()=>changeStatus("SHORTLISTED")}><Check size={16}/> Shortlist</button><button className="danger" onClick={()=>changeStatus("REJECTED")}><X size={16}/> Reject</button><button className="secondary"><Mail size={16}/> Contact candidate</button></div></aside></div>
 </HRLayout>}
